### ISSUE TITLE
Incorrect request xml structure

### ISSUE THREAD

**Issue by qutella** [savonrb/savon#699] opened 2015-06-22 20:08 UTC
Hello.

I have such structure at the wsdl: 

```
<message name="sale">
    <part name="params" type="typens:PayTechniqueSoapSaleRequest"/>
</message>
```

And I have a working php script which uses this wsdl and performs SOAP requests.
When I write the same script with ruby, using savon, it doesn't work. 

I've compared both requests.

PHP:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:PayTechnique" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <SOAP-ENV:Body>
        <ns1:sale>
            <params xsi:type="ns1:PayTechniqueSoapSaleRequest">
                .... parameters list
            </params>
        </ns1:sale>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Savon:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:typens="urn:PayTechnique" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <typens:sale>
      .... parameters list
    </typens:sale>
  </env:Body>
</env:Envelope>
```

PHP wraps parameters in one more "params" tag. I'm not very familiar with SOAP, so I don't know if this is right or not. But request from php works and request from ruby don't.

When I explictly denote that parameters should be wrapped in "params" tag, everything works  

``` ruby
client.call(:sale, message: {params: params})
```

I want to know, if it is a bug or not and, if not, how should I handle such situations.
Thank you.

**Comment by tjarratt** [comment] 2015-06-24 05:01
Hey @qutella thanks for filing this issue. We've had a rash of problems like this lately and I'm not entirely sure where the problem is. If you're up to do some investigation, I'd be more than happy to merge any pull requests that fix this for you.

You might want to start off by looking at [Wasabi](https://github.com/savonrb/wasabi) -- it handles converting the WSDL into a ruby object so Savon can know what operations can be performed (and how to create the requests).

**Comment by jonathanpa** [comment] 2015-07-21 12:15
Just to say I get the same problem :+1:

**Comment by fernandes** [comment] 2016-03-03 01:31
@tjarratt I got the same problem with this wsdl file https://api.softlayer.com/soap/v3.1/SoftLayer_Brand?wsdl

```xml
<message name="createObject">
  <part name="templateObject" type="tns:SoftLayer_Brand"/>
</message>
```

savon is generating

```xml
<tns:createObject>
  <templateObject>
  </templateObject>
</tns:createObject>
```

and should be

```xml
<createObject>
  <templateObject xsi:type="tns:SoftLayer_Brand">
  </templateObject>
</createObject>
```

I'm going to dig into wasabi as you suggested... thank you!

**Comment by fernandes** [comment] 2016-03-03 01:46
@tjarratt [here](https://github.com/savonrb/wasabi/blob/6da174e56c4f0a502f49ea65210260a8e3c6a8f0/lib/wasabi/parser.rb#L274) bypassing the `part` element... still investigating how could fix, I wrote a test and now trying to make it pass

**Comment by fernandes** [comment] 2016-03-03 02:31
@tjarratt please correct if I'm wrong (I'm new to soap)

but seems the wsdl for @qutella and mine are rpc/encoded, while wasabi just support Document/literal, where it searchs for an `element` attribute then looks for the type, correct?

**Comment by fernandes** [comment] 2016-03-03 14:57
@qutella and @tjarratt I created this PR https://github.com/savonrb/savon/pull/744 to discuss a possible solution to this problem.

I tested here with the SoftLayer client I developed and it's working flawlessly, any feedback on solution design, uncovered edge cases or code style is appreciated.

**Comment by fernandes** [comment] 2016-03-04 13:58
@qutella my PR was merged, could you please try the code on master then if resolved, I think this issue can be closed

**Closed** 2018-02-26 22:59 UTC
Labels: wontfix
