### ISSUE TITLE
booleans behavior changed between 2.11.1 and 2.11.2?

### ISSUE THREAD

**Issue by jaypatrickhoward** [savonrb/savon#826] opened 2017-08-16 16:11 UTC
I recently updated our project from 2.11.1 to 2.11.2, and one of our engineers noted the following:

The request:

    request = {
        'CustNumber' => 1234,
        'AcctFilter' => 'xyz',
        'IncludeClosedFlag' => false, #boolean
    }

...gets turned into the following in 2.11.1:

    <tns:AcctDetailsRq xmlns="EDITED">
      <tns:CustNumber>1234</tns:CustNumber>
      <tns:AcctFilter>xyz</tns:AcctFilter>
      <tns:IncludeClosedFlag>false</tns:IncludeClosedFlag>
    </tns:AcctDetailsRq>   

In 2.11.2, however, it turns into this:

    <tns:AcctDetailsRq xmlns="EDITED">
      <tns:CustNumber>1234</tns:CustNumber>
      <tns:AcctFilter>xyz</tns:AcctFilter>
      <tns:IncludeClosedFlag xsi:nil="true"/>
    </tns:AcctDetailsRq>   

The "IncludeClosedFlag" field expects a string.  2.11.1 converts the boolean to a string value (e.g. "true" or "false") whereas 2.11.2 omits it and sends a nil value.

Is that the new behavior, or a bug?

**Comment by lloeki** [comment] 2017-08-17 09:44
Our workaround for now is something to the effect of:

```
request = {
    'CustNumber' => 1234,
    'AcctFilter' => 'xyz',
    'IncludeClosedFlag' => false.to_s, #convert boolean to string on message hash building, to_s since we have it in a variable
}
```

**Comment by jaypatrickhoward** [comment] 2017-08-17 13:41
Well, yeah, we could solve this by modifying a bunch of code.  If it's not intended behavior then I may just pin to 2.11.1 until a fix is released, rather than deploy that workaround everywhere.  Just trying to determine whether it's unintended (i.e. may eventually be restored to the old behavior) or intended (i.e. probably never going back to the old way).

At least I know I'm not alone.  :)

**Comment by pcai** [comment] 2017-08-17 14:06
Thank you both. It sounds like this bug may not originate in savon, so I'll be monitoring this thread for more information.

**Comment by jaypatrickhoward** [comment] 2017-08-17 14:34
I haven't verified personally, but my engineer is claiming that switching from 2.11.2 back to 2.11.1 caused the "nil issue" to go away without making any other gem changes.  But lloeki has said he also sees the behavior with 2.11.1, so maybe there are multiple different ways this can happen.

**Comment by lloeki** [comment] 2017-08-17 15:27
Wait a minute, I think I looked at the wrong place somehow. Just to be sure I ran a last minute check:

```
$ bundle show savon
/srv/www/production/redacted/shared/bundle/ruby/2.3.0/gems/savon-2.11.2
```

Damn. Sorry for having mixed things up somehow.

**Comment by swatosh** [comment] 2017-08-23 03:07
We're seeing this problem at $WORK$ and had to revert to 2.11.1.

I'm GUESSING here, but perhaps the first line changed in the to_hash method
in lib/savon/qualified_message.rb
<https://github.com/savonrb/savon/commit/fbe0d130f35996bccc422def7e382fa1468a5332#diff-fd57500908edafac7334224f9393a300>
in
https://github.com/savonrb/savon/commit/fbe0d130f35996bccc422def7e382fa1468a5332
looks like it might inadvertently convert a false to a nil.

WDYT?
--
Joe

PS New to github, I'm going to try to leave a comment on the commit itself.
Sorry for over-notifications!

**Comment by pcai** [comment] 2017-08-23 04:00
Hi @swatosh thanks for investigating this. I think your hunch may be correct. 

Anyone here able to contribute a failing rspec test? I'm a bit overloaded this week and next (I'm moving...) but a test case would help a lot in creating and confirming any fix, and I'm happy to release a new minor version once it lands in master.

**Comment by swatosh** [comment] 2017-08-23 12:57
Excellent. I forgot to say that it's all theoretical at at this point, I
haven't had a chance to actually try it. I hope someone gets to it before
me, because I won't have a chance for the next couple of weeks.

**Comment by skoona** [comment] 2017-08-24 21:45
#830 relates to failure outcomes from release tag 2.11.2 and I included XML of the issue, which is a namespace failure.

**Comment by pcai** [comment] 2017-09-27 02:34
Hi all, closing this issue now that #833 is merged. Thank you all for your help chasing down this regression. I will cut a bugfix release as soon as I can.

**Closed by pcai** 2017-09-27 02:34 UTC
