### ISSUE TITLE
Invalid version of rubyntlm

### ISSUE THREAD

**Issue by arashm** [savonrb/savon#674] opened 2015-03-11 10:39 UTC
When requiring savon I get this message:

```
ArgumentError: Invalid version of rubyntlm. Please use v0.3.2+.
from ~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi/adapter/net_http.rb:12:in `<top (required)>'
```

The next time I require savon I get this:

```
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:3: warning: already initialized constant Savon::Error
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:3: warning: previous definition of Error was here
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:4: warning: already initialized constant Savon::InitializationError
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:4: warning: previous definition of InitializationError was here
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:5: warning: already initialized constant Savon::UnknownOptionError
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:5: warning: previous definition of UnknownOptionError was here
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:6: warning: already initialized constant Savon::UnknownOperationError
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:6: warning: previous definition of UnknownOperationError was here
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:7: warning: already initialized constant Savon::InvalidResponseError
~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:7: warning: previous definition of InvalidResponseError was here
ArgumentError: Invalid version of rubyntlm. Please use v0.3.2+.
from ~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi/adapter/net_http.rb:12:in `<top (required)>'
```

I'm using savon `2.10.1`  and rubyntlm `0.5.0` is installed.

**Comment by tjarratt** [comment] 2015-03-12 04:41
Hello @arashm -- what you describe isn't really making sense. I tried to reproduce this locally by installing rubyntlm `0.5.0` and this simple example works as expected:

```shell
± bundle exec irb
2.1.2 :001 > require 'rubyntlm'
 => true 
2.1.2 :004 > require 'net/ntlm'
 => false 
2.1.2 :006 > require 'net/ntlm/version'
 => true 
2.1.2 :007 > Net::NTLM::VERSION::STRING
 => "0.5.0" 
2.1.2 :008 > Net::NTLM::VERSION::STRING >= "0.3.2"
 => true 
2.1.2 :009 > require 'savon'
 => true 
2.1.2 :010 > Savon::VERSION
 => "2.10.1" 
2.1.2 :010 > 
```

The latter warning ... is quite suspicious. Exactly how are you requiring savon? This warning shouldn't show up if you simply `require 'savon'`.

```shell
bundle exec irb
2.1.2 :001 >   require 'savon'
 => true 
2.1.2 :001 > require 'savon'
 => false 
```

**Comment by arashm** [comment] 2015-03-12 07:33
Hello @tjarratt thanks for response.
I just tested savon with bundler and it worked. But I'm getting the same error without bundler. I still get the error if I run IRB or Pry without `bundle exec`.

**Comment by tjarratt** [comment] 2015-03-13 04:46
Hmm, well that's interesting. Could you tell me a little bit more about how this problem manifests?

* Exactly how are you requiring Savon? (e.g.: `require 'savon', or something similar). A lot of output from your irb or pry session here would be interesting.
* Which version of ruby are you using?

**Comment by arashm** [comment] 2015-03-13 10:35
I just type `require 'savon'` for requiring savon :smile:. In IRB when I type `require 'savon'` and press enter I get this:

```
ArgumentError: Invalid version of rubyntlm. Please use v0.3.2+.
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi/adapter/net_http.rb:12:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi.rb:9:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon/options.rb:2:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon/operation.rb:1:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon/client.rb:1:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:26:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from /home/arashm/.rbenv/versions/2.1.5/bin/irb:11:in `<main>'irb(main):002:0> 
```

The second time I do `require 'savon'` on the same session I get this:

```
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:3: warning: already initialized constant Savon::Error
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:3: warning: previous definition of Error was here
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:4: warning: already initialized constant Savon::InitializationError
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:4: warning: previous definition of InitializationError was here
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:5: warning: already initialized constant Savon::UnknownOptionError
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:5: warning: previous definition of UnknownOptionError was here
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:6: warning: already initialized constant Savon::UnknownOperationError
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:6: warning: previous definition of UnknownOperationError was here
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:7: warning: already initialized constant Savon::InvalidResponseError
/home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:7: warning: previous definition of InvalidResponseError was here
ArgumentError: Invalid version of rubyntlm. Please use v0.3.2+.
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi/adapter/net_http.rb:12:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/httpi-2.3.0/lib/httpi.rb:9:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon/options.rb:2:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon/operation.rb:1:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon/client.rb:1:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/savon-2.10.1/lib/savon.rb:26:in `<top (required)>'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/arashm/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from (irb):2
```

From the errors you can see that I'm using Ruby 2.1.5.

**Comment by tjarratt** [comment] 2015-03-15 01:37
Could you also include the commands you're running? Maybe the entire session from invoking irb and the require statements?

What you're describing is [strange](http://ruby-doc.org/core-2.2.1/Kernel.html#method-i-require) because `require` isn't supposed to actually evaluate files multiple times. The only time I've seen this in the past is when someone was using a case-insensitive and they typed `require 'Savon'` (with a capital S) after having previously typed `require 'savon'`. Is it possible you're doing something similar?

**Comment by arashm** [comment] 2015-03-22 08:48
Sorry for responding late.
There's nothing special in commands I enter. Just `irb` and then `require 'savon'`. That's it.

**Comment by bradex** [comment] 2015-03-23 03:08
@arashm

I got the same "Invalid version of rubyntlm" error.
In my case, "gem uninstall ntlm-http" solved the problem.

**Comment by alexbel** [comment] 2015-03-26 19:04
I have the same issue.
`ArgumentError: Invalid version of rubyntlm. Please use v0.3.2+`

**Comment by markadrianagbuya** [comment] 2015-03-31 01:06
I'm also having the same issue.

**Comment by tjarratt** [comment] 2015-04-01 04:48
@arashm and @alexbel  I'm sorry but I'm going to close this issue. I'm not convinced this is a real issue. I would love to be wrong, so if someone has a compelling reason for something in Savon to change that makes this better, please let me know so we can fix it. :)

**Closed by tjarratt** 2015-04-01 04:48 UTC
