### ISSUE TITLE
Assigning false value generates empty tag in 2.11.2

### ISSUE THREAD

**Issue by mrstif** [savonrb/savon#850] opened 2017-12-19 18:53 UTC
I recently upgraded Savon from `2.11.1` to `2.11.2`. When I'm assigning a boolean value to a property, the request generated is now different in what doesn't seem like expected behaviour.

Considering a message like `{ something: false }`:

*2.11.1*
generates `<Something>false</Something>`

*2.11.2*
generates `<Something xsi:nil="true"/>`

Is this expected? If so, is there any option to the client to prevent this from happening?

**Comment by pcai** [comment] 2018-01-17 00:14
this is a dupe of https://github.com/savonrb/savon/issues/826

**Closed by pcai** 2018-01-17 00:14 UTC
