### ISSUE TITLE
Mapping ruby Hash to XML seems to depend on order of inserting keys

### ISSUE THREAD

**Issue by darrenleeweber** [savonrb/savon#859] opened 2018-02-07 03:15 UTC
It seems that a ruby hash enumerates by the order of inserting keys (is that right?)
- https://stackoverflow.com/questions/11350500/ruby-hash-keys-and-values-safe-to-assume-same-order

When composing params for a SOAP message using a Hash, we are getting SOAPFault errors related to XSD validation failures that depend on the order of XML elements.  We cannot insert new key:value pairs into a Hash because it seems to mess up the resulting XML element order.

How does savon map the Hash key:value pairs to XML elements?  Can it use the WSDL to correctly pluck out the key:value pairs in the correct order?

**Comment by pcai** [comment] 2018-03-25 03:43
Thanks for contributing. Closing this since it seems to be a dupe of 592.

**Closed by pcai** 2018-03-25 03:43 UTC
